### ISSUE TITLE
about the train log?

### ISSUE THREAD

**Issue by ZHUXUHAN** [aa200647963/SGG-DHL#1]
hi, can you provide the model or log file of your model? thank you very much!

**Comment by aa200647963** [comment]
I will provide the Transformer Model of PredCls task.



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 5, 2022 17:58 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [aa200647963/SGG-DHL] about the train log? (Issue #1)




 
hi, can you provide the model or log file of your model? thank you very muck!

**Comment by ZHUXUHAN** [comment]
ok! thanks.

**Comment by aa200647963** [comment]
I have provided the model and log files, read the README.md.

**Comment by ZHUXUHAN** [comment]
> I have provided the model and log files, read the README.md.

hi，i see it, thanks for your share.
