### ISSUE TITLE
about the new version of your paper?

### ISSUE THREAD

**Issue by ZHUXUHAN** [aa200647963/SGG-DHL#2]
i see your new version paper. there is caption experiments. 
Not sure if you have any plans to open source code for this part, I'm doing similar research recently and hope to get some inspiration from your research. Many thanks for this.

**Comment by aa200647963** [comment]
My classmate helped me do this part, so I need to ask for his advice. If allowed, I will release the code in the near future

**Comment by ZHUXUHAN** [comment]
> My classmate helped me do this part, so I need to ask for his advice. If allowed, I will release the code in the near future

ok. Your work is the best job recently, it is very valuable. Thank you for your sharing
