### ISSUE TITLE
about the hyperreference settings of vctree and motif?

### ISSUE THREAD

**Issue by ZHUXUHAN** [aa200647963/SGG-DHL#5]
hi, dear sir.
can you update the scripts of vctree and motif?
i just use the same hyperreference settings of transformer with vctree model, but the precision is bad. 
so hope you can provide the scripts.

**Comment by aa200647963** [comment]
I made the VCTree model the same as Transformer, using the sum of the results of the two classifiers as the final result, I don't know if you haven't changed it here `rel_dists = self.rel_compress(visual_rep) + self.ctx_compress(prod_rep)` . I provide the log file for your reference
[log.txt](https://github.com/aa200647963/SGG-DHL/files/9347510/log.txt)
