### ISSUE TITLE
About the installation of maskrcnn_benchmark

### ISSUE THREAD

**Issue by Infinitywxh** [aa200647963/SGG-DHL#7]
Hi, I have a question about the installation. In INSTALL.md you install maskrcnn_benchmark from https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch.git, while in the repository you provide a directory of maskrcnn_benchmark, which seems to be different. I wonder which one should I install then?

**Comment by aa200647963** [comment]
Hello, you can download my repo and install it according to the guidelines in INSTALL.MD

**Comment by aa200647963** [comment]
For **git clone" https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch.git ,** just use my repo.
